language: ruby

before_install:
  - ./travis/deps.sh

before_script:
  - ./travis/prep.sh

services:
  - redis-server
  - cassandra

rvm:
  - 2.0.0
  - 2.1.4
  - 2.2.2
  - ruby-head
  - jruby-20mode
  - rbx-2

matrix:
  include:
    - rvm: jruby-20mode
      env: JRUBY_OPTS="$JRUBY_OPTS --2.0"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-20mode
    - rvm: rbx-2
    - env: DCELL_TEST_ADAPTER=cassandra
    - env: DCELL_TEST_ADAPTER=zk

branches:
  only:
    - master

env:
    - DCELL_TEST_ADAPTER=redis
    - DCELL_TEST_ADAPTER=cassandra
    - DCELL_TEST_ADAPTER=zk
